config/routes.rb
Rails.application.routes.draw do

  root to: "noobs#index"

  post '/noobs/:id/follow(.:format)', action: :follow, controller: :noobs, as: :follow_noob
  post '/noobs/:id/unfollow(.:format)', action: :unfollow, controller: :noobs, as: :unfollow_noob
  post '/noobs/:id/im_bad(.:format)', action: :im_bad, controller: :noobs, as: :im_bad_noob
  get '/noobs/follows', action: :follows, controller: :noobs
  resources :noobs do
    resources :marks
  end

  resources :marks

  devise_for :users
  resources :users

end

app/models/mark.rb
class Mark < ActiveRecord::Base
  belongs_to :noob

  def noob_name
    Noob.find_by(id: noob_id).name rescue ""
  end

  def noob_name= name
    self.noob = Noob.find_by(name: name)
    puts "I'm setting the noob : #{name} => #{noob_id}"
  end

end

app/controllers/marks_controller.rb
class MarksController < ApplicationController
  before_action :admin_page!
  before_action :set_mark, only: [:show, :edit, :update, :destroy]

  # GET /marks
  # GET /marks.json
  def index
    @marks = Mark.all
  end

  # GET /marks/1
  # GET /marks/1.json
  def show
  end

  # GET /marks/new
  def new
    @mark = Mark.new
  end

  # GET /marks/1/edit
  def edit
  end

  # POST /marks
  # POST /marks.json
  def create
    @mark = Mark.new(mark_params)

    respond_to do |format|
      if @mark.save
        format.html { redirect_to @mark, notice: 'Mark was successfully created.' }
        format.json { render :show, status: :created, location: @mark }
      else
        format.html { render :new }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marks/1
  # PATCH/PUT /marks/1.json
  def update
    respond_to do |format|
      if @mark.update(mark_params)
        format.html { redirect_to @mark, notice: 'Mark was successfully updated.' }
        format.json { render :show, status: :ok, location: @mark }
      else
        format.html { render :edit }
        format.json { render json: @mark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marks/1
  # DELETE /marks/1.json
  def destroy
    @mark.destroy
    respond_to do |format|
      format.html { redirect_to marks_url, notice: 'Mark was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mark
      @mark = Mark.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mark_params
      params[:mark].permit(:value, :noob_id, :noob_name)
    end
end

app/helpers/marks_helper.rb
module MarksHelper
end

app/views/marks/_form.html.slim
= form_for @mark do |f|
  - if @mark.errors.any?
    #error_explanation
      h2 = "#{pluralize(@mark.errors.count, "error")} prohibited this mark from being saved:"
      ul
        - @mark.errors.full_messages.each do |message|
          li = message

  == f.text_field :value, class: 'form-control input-sm', pattern: '[\-0-9]{0,10}', title: 'only \-0-9, size 0..10', placeholder: "value"
  == f.text_field :noob_name, class: 'form-control input-sm',  pattern: '[a-z\-_0-9]{2,10}', title: 'only a-Z,-,_,0-9, size 2..10', placeholder: "username"
  / == f.hidden_field :noob_id
  .actions = f.submit class: "btn btn-sm btn-success noobCreateLink"

app/views/marks/edit.html.slim
h1 Editing mark

== render 'form'

= link_to 'Show', @mark
'|
= link_to 'Back', marks_path

app/views/marks/index.html.slim
h1 Listing marks

table.table.table-condensed
  thead
    tr
      th.col-xs-1 Mark

  tbody
    - @marks.each do |mark|
      tr
        td = mark.value
        td = link_to 'Show', mark
        td = link_to 'Edit', edit_mark_path(mark)
        td = link_to 'Destroy', mark, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Mark', new_mark_path

app/views/marks/new.html.slim
h1 New mark

== render 'form'

= link_to 'Back', marks_path

app/views/marks/show.html.slim
p#notice = notice

p
  | Note : #{@mark.value}

= link_to 'Edit', edit_mark_path(@mark)
'|
= link_to 'Back', marks_path