config/routes.rb
Rails.application.routes.draw do

  root to: "noobs#index"

  post '/noobs/:id/follow(.:format)', action: :follow, controller: :noobs, as: :follow_noob
  post '/noobs/:id/unfollow(.:format)', action: :unfollow, controller: :noobs, as: :unfollow_noob
  post '/noobs/:id/im_bad(.:format)', action: :im_bad, controller: :noobs, as: :im_bad_noob
  get '/noobs/follows', action: :follows, controller: :noobs
  resources :noobs do
    resources :marks
  end

  resources :marks

  devise_for :users
  resources :users

end

app/models/noob.rb
class Noob < ActiveRecord::Base
  has_many :follows
  has_many :users, through: :follows
  has_many :followers, through: :follows, source: :user, class_name: :User, foreign_key: :user_id
  has_many :marks
  self.per_page = 50

  validates :name, format: { with: /[[:alnum:]_\-]{2,10}/, message: 'only a-Z,-,_,0-9, size 2..10' }
  validates :name, uniqueness: true

  before_save :default_bad
  def default_bad
    self.bad ||= 0
  end

  def find_lock_for_user u
    LockBad.find_by(user: u, noob: self)
  end

  def locked_for_user? u
    #return false
    return false if u.admin?
    lock = find_lock_for_user u
    if lock and lock.updated_at > LockBad::TIMEOUT
      return true
    else
      return false
    end
  end

  def lock_for_user! u
    lock = find_lock_for_user u
    if lock
      return lock.update!(updated_at: Time.now)
    else
      return LockBad.create!(noob: self, user: u)
    end
  end
end

app/controllers/noobs_controller.rb
class NoobsController < ApplicationController
  before_action :set_noob, only: [:show, :edit, :update, :destroy, :follow, :unfollow, :im_bad]
  before_action :admin_page!, only: [:edit, :update, :destroy, :new, :create]
  before_action :set_followed, only: [:index, :follows]

  def follow_response
    respond_to do |format|
      format.js {render json: @noob, status: :ok}
      format.html {redirect_to noobs_url}
    end
  end

  def follow
    current_user.noobs.push @noob
    follow_response
  end

  def unfollow
    current_user.noobs.delete @noob
    follow_response
  end

  def im_bad_successfull_lock
    @noob.lock_for_user! current_user # generate / update the lockBad
    respond_to do |format|
      format.js {render json: @noob, status: :ok}
      format.html {redirect_to noobs_url}
    end
  end

  def im_bad_failed_lock
    respond_to do |format|
      if @noob.locked_for_user?(current_user)
        format.js {render json: @noob, status: :locked}
      else
        format.js {render json: @noob, status: :unprocessable_entity}
      end
      format.html {redirect_to noobs_url}
    end
  end

  def im_bad
    # successfully is true only if not locked in last 7 days and updated successfully
    successfully = !@noob.locked_for_user?(current_user) && @noob.update(bad: @noob.bad+1)
    if successfully
      im_bad_successfull_lock
    else
      im_bad_failed_lock
    end
  end

  # GET /noobs
  # GET /noobs.json
  def index
    @noob = Noob.new if current_user.admin?
    @noobs = Noob.order(:bad).reverse_order
    @noobs = search_name(@noobs) if params[:noob_search]
    @noobs = @noobs.paginate(page: params[:page])
  end

  def follows
    @noob = Noob.new if current_user.admin?
    @noobs = current_user.noobs.order(:bad).reverse_order
    @noobs = search_name(@noobs) if params[:noob_search]
    @noobs = @noobs.paginate(page: params[:page])
    render :index
  end

  # GET /noobs/1
  # GET /noobs/1.json
  def show
    @mark = Mark.new
    @mark.noob_id = @noob.id
  end

  # GET /noobs/new
  def new
    @noob = Noob.new
  end

  # GET /noobs/1/edit
  def edit
    @mark = Mark.new
    @mark.noob_id = @noob.id
  end

  # POST /noobs
  # POST /noobs.json
  def create
    @noob = Noob.new(noob_params)

    respond_to do |format|
      if @noob.save
        format.html { redirect_to @noob, notice: 'Noob was successfully created.' }
        format.json { render json: @noob, status: :created }
      else
        format.html { render :new }
        format.json { render json: @noob.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /noobs/1
  # PATCH/PUT /noobs/1.json
  def update
    respond_to do |format|
      if @noob.update(noob_params)
        format.html { redirect_to @noob, notice: 'Noob was successfully updated.' }
        format.json { render json: @noob, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @noob.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /noobs/1
  # DELETE /noobs/1.json
  def destroy
    @noob.destroy
    respond_to do |format|
      format.html { redirect_to noobs_url, notice: 'Noob was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noob
      @noob = Noob.find(params[:id])
    end

    def set_followed
      @followed = current_user.noobs
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def noob_params
      params.require(:noob).permit(:name, :bad)
    end

    def search_name(noobs)
      # TODO : check if safe
      query = params[:noob_search].to_s.gsub(/[^[:alnum:]]/, '')
      noobs = noobs.where("noobs.name LIKE('%#{query}%')")
    end
end

app/helpers/noobs_helper.rb
module NoobsHelper
end

app/views/noobs/_form.html.slim
- if not defined? locals
  - locals = {}
== form_for(@noob, {data: {type: :json}, remote: locals[:remote], role: 'form', html: {class: (locals[:inline] ? 'form-inline' : '')}}) do |f|
  - if @noob.errors.any?
    #error_explanation
      h2 = "#{pluralize(@noob.errors.count, "error")} prohibited this noob from being saved:"

      ul
        - @noob.errors.full_messages.each do |message|
        li = message
  - if locals[:inline]
    == f.submit (locals[:button_label] || "Create Noob"), class: "btn btn-sm btn-success noobCreateLink"
  - if locals[:name].nil? or locals[:name] == true
    == f.text_field :name, class: 'form-control input-sm', pattern: '[a-z\-_0-9]{2,10}', title: 'only a-Z,-,_,0-9, size 2..10', placeholder: "username"
  - if locals[:bad].nil? or locals[:bad] == true
    == f.text_field :bad, class: 'form-control input-sm', pattern: '[\-0-9]{0,10}', title: 'only \-0-9, size 0..10', placeholder: "bad"
  - if not locals[:inline]
    .actions = f.submit (locals[:button_label] || "Create Noob"), class: "btn btn-sm btn-success noobCreateLink"

app/views/noobs/_form_search.html.slim
- if not defined? locals
  - locals = {}
== form_tag nil, {method: :get, remote: locals[:remote], class: 'form-inline'} do |f|
  == text_field_tag :noob_search, params[:noob_search], class: 'form-control input-sm'
  == submit_tag 'Search Noob', class: "btn btn-sm btn-success"

app/views/noobs/edit.html.slim
h1 Editing noob

== render 'form', locals: {button_label: "Update Noob"}
== render 'marks/form'

== link_to 'Show', @noob, class: 'btn btn-sm btn-default'
== link_to 'Back', noobs_path, class: 'btn btn-sm btn-default'

app/views/noobs/index.html.slim
h1 Listing noobs

.container-fluid
  .row
    .pull-left
      - if current_user.admin?
        == render 'form', locals: {remote: true, inline: true, bad: false}
    .pull-right
      == render 'form_search'

== will_paginate @noobs

table.table.table-condensed
  thead
    tr
      th.col-xs-1 ID
      th.col-xs-2 Noobname
      th.col-xs-1 Bads
      - if params[:action] == 'follows'
        th.col-xs-1 = link_to 'All', noobs_path
      - else
        th.col-xs-1 = link_to 'Follows', noobs_path + '/follows'
      td.col-xs-2 colspan='3' Actions
      th.col-xs-6

  tbody#noob-list
    - @noobs.each do |noob|
      tr id="noobLine_#{noob.id}" class='noobLine'
        td id="noobId_#{noob.id}" class='noobId' = "##{noob.id}"
        td id="noobName_#{noob.id}" class='noobName' = noob.name
        td
          span id="noobBad_#{noob.id}" class='noobBad' = "#{noob.bad} "
          = link_to( \
          "<span class='glyphicon glyphicon-plus'></span>".html_safe, im_bad_noob_path(noob), \
          remote: true, 'data-type' => :json, method: 'POST', \
          class: 'noobImBad', id: "noobImBad_#{noob.id}")
        td = link_to( \
        *(@followed.include?(noob) ? ["<span class='glyphicon glyphicon-star'></span>".html_safe, unfollow_noob_path(noob) ] :\
        ["<span class='glyphicon glyphicon-star-empty'></span>".html_safe, follow_noob_path(noob) ] ), \
        remote: true, 'data-type' => :json, method: 'POST', \
        class: 'btn btn-default btn-sm noobFollowLink', id: "noobFollowLink_#{noob.id}")
        td = link_to 'Show', noob, \
        class: 'btn btn-default btn-sm noobShowLink', id: "noobShowLink_#{noob.id}"
        - if current_user.admin?
          td = link_to 'Edit', edit_noob_path(noob), \
          class: 'btn btn-default btn-sm noobEditLink', id: "noobEditLink_#{noob.id}"
          td = link_to 'Destroy', noob, \
          class: 'btn btn-default btn-sm noobDestroyLink', id: "noobDestroyLink_#{noob.id}", \
          remote: true, 'data-type' => :json, \
          data: {:confirm => 'Are you sure?'}, :method => :delete
        - else
          td
          td
        td

app/views/noobs/new.html.slim
h1 New noob

== render 'form', locals: {button_label: "Create Noob"}

== link_to 'Back', noobs_path, class: 'btn btn-sm btn-default'

app/views/noobs/show.html.slim
h2 = @noob.name
h4#bad
  | bad :
  | #{@noob.bad} bad
  |  &&
  | (#{@noob.marks.count})

table.table.table-condensed
  tr
    th.col-xs-1 Note
    td.col-xs-3 Commentaire
  - @noob.marks.each do |mark|
    tr
      td = mark.value
      td = mark.note

== render 'marks/form'

== link_to 'Edit', edit_noob_path(@noob), class: 'btn btn-sm btn-default'
== link_to 'Back', noobs_path, class: 'btn btn-sm btn-default'